version: '3'
services:
    db:
        platform: linux/amd64
        image: mysql:8.0.26
        container_name: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: Rese_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: password123
            TZ: 'Asia/Tokyo'
        # ポートフォワードの指定（ホスト側ポート：コンテナ側ポート）
        ports:
            - 4306:3306
        # コマンドの指定
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        # 名前付きボリュームを設定する（名前付きボリューム:コンテナ側ボリュームの場所）
        volumes:
            - db_data_test:/var/lib/mysql
            - db_my.cnf_test:/etc/mysql/conf.d/my.cnf
            - db_sql_test:/docker-entrypoint-initdb.d

    php:
        build: ./docker/php
        container_name: 'php-fpm'
        # Vueとの接続を許可する
        ports:
            - 5173:5173
        # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
        volumes:
            - ./src:/var/www

    nginx:
        image: nginx:latest
        container_name: 'nginx'
        # ポートフォワードの指定（ホスト側ポート：コンテナ側ポート）
        ports:
            - 80:80
        # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        # サービスの依存関係を指定（nginxをphpに依存させる）
        depends_on:
            - php

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: 'phpmyadmin'
        environment:
            - PMA_ARBITRARY=1 # サーバ設定：サーバーをローカル以外も指定
            - PMA_HOST=db # ホスト設定：dbを指定
            - PMA_USER=admin # 初期ユーザー設定：adminを指定
            - PMA_PASSWORD=password123 # 初期PW設定：password123を指定
        # db（サービス名）とのリンクを設定する
        links:
            - db
        # ポートフォワードの指定（ホスト側ポート：コンテナ側ポート）
        ports:
            - 8080:80
        # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
        volumes:
            - ./phpmyadmin/sessions:/sessions

    mail:
        image: mailhog/mailhog
        container_name: 'mailhog'
        # ポートフォワードの指定（ホスト側ポート：コンテナ側ポート）
        ports:
            - 8025:8025

# サービスレベルで名前付きボリュームを命名する
volumes:
    db_data_test:
    db_my.cnf_test:
    db_sql_test:
